In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import tcellmatch.api as tm
import os
from sklearn.metrics import accuracy_score

In [60]:
# VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\machine_learning\data\VDJdb_TRA.tsv"
# VDJdb_TRA = pd.read_table("data/VDJdb_TRA.tsv")
# display(VDJdb_TRA)


# VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\machine_learning\data\processed_tra_by_giana_modify.tsv"
# VDJdb_TRA = pd.read_csv("data/Processed_TRA_by_GIANA.csv")
# VDJdb_TRA_Modify = VDJdb_TRA[["V1", "V5"]]
# VDJdb_TRA_Modify = VDJdb_TRA_Modify.rename(columns = {'V1': 'CDR3', 'V5': 'Epitope'})
# VDJdb_TRA_Modify['Gene'] = "TRA"
# VDJdb_TRA_Modify['complex.id'] = range(1,13988)
# VDJdb_TRA_Modify.to_csv("data/processed_tra_by_giana_modify.tsv", sep='\t', index=False)
# VDJdb_TRA = pd.read_table("data/processed_tra_by_giana_modify.tsv")
# display(VDJdb_TRA)



# VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\machine_learning\data\processed_trb_conf_by_giana_modify.tsv"
# VDJdb_TRA = pd.read_csv("data/Processed_TRB_Conf_by_GIANA.csv")
# VDJdb_TRA_Modify = VDJdb_TRA[["V1", "V5"]]
# VDJdb_TRA_Modify = VDJdb_TRA_Modify.rename(columns = {'V1': 'CDR3', 'V5': 'Epitope'})
# VDJdb_TRA_Modify['Gene'] = "TRB"
# VDJdb_TRA_Modify['complex.id'] = range(1,len(VDJdb_TRA_Modify.index)+1)
# VDJdb_TRA_Modify.to_csv("data/processed_trb_conf_by_giana_modify.tsv", sep='\t', index=False)
# VDJdb_TRA = pd.read_table("data/processed_trb_conf_by_giana_modify.tsv")
# display(VDJdb_TRA)

# VDJdb_TRA_Train = VDJdb_TRA.sample(frac=0.8)
# display(VDJdb_TRA_Train)
# VDJdb_TRA_Test = VDJdb_TRA.drop(VDJdb_TRA_Train.index)
# display(VDJdb_TRA_Test)
# VDJdb_TRA_Train.to_csv("Train_Test_data/VDJdb_TRA_Train.tsv", sep='\t')
# VDJdb_TRA_Test.to_csv("Train_Test_data/VDJdb_TRA_Test.tsv", sep='\t')
# display(VDJdb_TRA_Test)


# VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\machine_learning\data\processed_tra_conf_human.tsv"
# VDJdb_TRA = pd.read_csv("data/Processed_TRA_Conf_human.csv")
# display(VDJdb_TRA)
# VDJdb_TRA_Modify = VDJdb_TRA[["V1", "V6"]]
# VDJdb_TRA_Modify = VDJdb_TRA_Modify.rename(columns = {'V1': 'CDR3', 'V6': 'Epitope'})
# VDJdb_TRA_Modify['Gene'] = "TRA"
# VDJdb_TRA_Modify['complex.id'] = range(1,len(VDJdb_TRA_Modify.index)+1)
# VDJdb_TRA_Modify.to_csv("data/processed_tra_conf_human.tsv", sep='\t', index=False)
# VDJdb_TRA = pd.read_table("data/processed_tra_conf_human.tsv")
# display(VDJdb_TRA)


VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\machine_learning\data\processed_trb_human.tsv"
VDJdb_TRA = pd.read_csv("data/Processed_TRB_human.csv")
display(VDJdb_TRA)
VDJdb_TRA_Modify = VDJdb_TRA[["V1", "V6"]]
VDJdb_TRA_Modify = VDJdb_TRA_Modify.rename(columns = {'V1': 'CDR3', 'V6': 'Epitope'})
VDJdb_TRA_Modify['Gene'] = "TRB"
VDJdb_TRA_Modify['complex.id'] = range(1,len(VDJdb_TRA_Modify.index)+1)
VDJdb_TRA_Modify.to_csv("data/processed_trb_human.tsv", sep='\t', index=False)
VDJdb_TRA = pd.read_table("data/processed_trb_human.tsv")
display(VDJdb_TRA)

# VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\machine_learning\data\VDJdb_Conf_Paired_human_fix.tsv"
# VDJdb_TRA = pd.read_table("data/VDJdb_Conf_Paired_human.tsv")
# VDJdb_TRA_Modify = VDJdb_TRA[["cdr3_a_aa", "epitope_aa", "id"]]
# VDJdb_TRA_Modify = VDJdb_TRA_Modify.rename(columns = {'cdr3_a_aa': 'CDR3', 'epitope_aa': 'Epitope', 'id':'complex.id'})
# VDJdb_TRA_Modify['Gene'] = "TRA"
# VDJdb_TRA = VDJdb_TRA_Modify
# VDJdb_TRA.to_csv("data/VDJdb_Conf_Paired_human_fix.tsv", sep='\t', index=False)
# display(VDJdb_TRA)

# VDJdb_TRA_Train_path = "Train_Test_data/VDJdb_TRA_Train.tsv"
# VDJdb_TRA_Test_path = "Train_Test_data/VDJdb_TRA_Test.tsv"

Unnamed: 0                       V1    V2           V3  \
0          CASRGLAGVGVLSGYNEQFF     CASRGLAGVGVLSGYNEQFF     1  TRBV12-3*01   
1        CASRGLAGVGVLSGYNEQFF.1     CASRGLAGVGVLSGYNEQFF     1  TRBV12-3*01   
2          CASSFGPGWGNPSSYNEQFF     CASSFGPGWGNPSSYNEQFF     2  TRBV12-4*01   
3        CASSFGPGWGNPSSYNEQFF.1     CASSFGPGWGNPSSYNEQFF     2  TRBV12-4*01   
4          CASSFPVGGLAGAGYNEQFF     CASSFPVGGLAGAGYNEQFF     3     TRBV9*01   
...                         ...                      ...   ...          ...   
8141  CASSLRTGGFPSGTSGSTDTQYF.2  CASSLRTGGFPSGTSGSTDTQYF  2057   TRBV4-1*01   
8142     CASSFSLPAASDADRSGNTIYF   CASSFSLPAASDADRSGNTIYF  2058   TRBV7-9*01   
8143   CASSFSLPAASDADRSGNTIYF.1   CASSFSLPAASDADRSGNTIYF  2058   TRBV7-9*01   
8144     CASSPPPSGAKEGVRAGNTIYF   CASSPPPSGAKEGVRAGNTIYF  2059   TRBV3-1*01   
8145   CASSPPPSGAKEGVRAGNTIYF.1   CASSPPPSGAKEGVRAGNTIYF  2059   TRBV3-1*01   

              V4           V5          V6        V7  V8      V8.1  ...  \
0     TRBJ2-1*01  HomoSapiens   KLGGALQAK   1/25584   1 -0.444255  ...   
1     TRBJ2-1*01  HomoSapiens  AVFDRKSDAK   1/25584   1 -0.444255  ...   
2     TRBJ2-1*01  HomoSapiens   IVTDFSVIK    1/4761   1  0.808451  ...   
3     TRBJ2-1*01  HomoSapiens   KLGGALQAK    1/4761   1  0.808451  ...   
4     TRBJ2-1*01  HomoSapiens   KLGGALQAK   3/25584   3  0.373154  ...   
...          ...          ...         ...       ...  ..       ...  ...   
8141  TRBJ2-3*01  HomoSapiens  AVFDRKSDAK   1/11684   1 -1.017009  ...   
8142  TRBJ1-3*01  HomoSapiens   KLGGALQAK  19/25584  19 -0.015589  ...   
8143  TRBJ1-3*01  HomoSapiens   KLGGALQAK   1/25584   1 -0.015589  ...   
8144  TRBJ1-3*01  HomoSapiens   KLGGALQAK   5/25584   5 -0.033693  ...   
8145  TRBJ1-3*01  HomoSapiens  AVFDRKSDAK   1/25584   1 -0.033693  ...   

           V94       V95       V96       V97       V98       V99      V100  \
0     1.068186  1.097017  1.189806  0.653387 -0.907105 -1.126341 -1.108326   
1     1.068186  1.097017  1.189806  0.653387 -0.907105 -1.126341 -1.108326   
2     0.695710  0.632486  0.686097  0.672163 -0.747706 -0.264251 -1.162510   
3     0.695710  0.632486  0.686097  0.672163 -0.747706 -0.264251 -1.162510   
4     1.068186  1.097017  1.189806  0.653387 -0.907105 -1.126341 -1.108326   
...        ...       ...       ...       ...       ...       ...       ...   
8141  0.896378  0.405223 -0.842522 -0.015613 -0.658883  0.499942  0.236501   
8142  0.351074  0.194336 -0.235214  0.909038 -0.052979  0.646169 -1.137917   
8143  0.351074  0.194336 -0.235214  0.909038 -0.052979  0.646169 -1.137917   
8144  0.217296  0.136737 -0.744012  0.781667  0.776502  0.395580 -0.450793   
8145  0.217296  0.136737 -0.744012  0.781667  0.776502  0.395580 -0.450793   

          V101      V102      V103  
0     0.362357 -1.432017 -0.179796  
1     0.362357 -1.432017 -0.179796  
2     0.775538 -1.010747  0.396517  
3     0.775538 -1.010747  0.396517  
4     0.362357 -1.432017 -0.179796  
...        ...       ...       ...  
8141  0.705056 -0.624847  0.605600  
8142  1.693368 -0.859197  0.448662  
8143  1.693368 -0.859197  0.448662  
8144  1.603658 -0.834180 -0.561921  
8145  1.603658 -0.834180 -0.561921  

[8146 rows x 105 columns]

CDR3     Epitope Gene  complex.id
0        CASRGLAGVGVLSGYNEQFF   KLGGALQAK  TRB           1
1        CASRGLAGVGVLSGYNEQFF  AVFDRKSDAK  TRB           2
2        CASSFGPGWGNPSSYNEQFF   IVTDFSVIK  TRB           3
3        CASSFGPGWGNPSSYNEQFF   KLGGALQAK  TRB           4
4        CASSFPVGGLAGAGYNEQFF   KLGGALQAK  TRB           5
...                       ...         ...  ...         ...
8141  CASSLRTGGFPSGTSGSTDTQYF  AVFDRKSDAK  TRB        8142
8142   CASSFSLPAASDADRSGNTIYF   KLGGALQAK  TRB        8143
8143   CASSFSLPAASDADRSGNTIYF   KLGGALQAK  TRB        8144
8144   CASSPPPSGAKEGVRAGNTIYF   KLGGALQAK  TRB        8145
8145   CASSPPPSGAKEGVRAGNTIYF  AVFDRKSDAK  TRB        8146

[8146 rows x 4 columns]

In [61]:
TCR_Predict_Target = list(set(VDJdb_TRA["Epitope"].tolist()))
print(type(TCR_Predict_Target))
#print(TCR_Predict_Target)

<class 'list'>


In [63]:
ffn = tm.models.EstimatorBinary()

ffn.read_vdjdb_as_categorical_model(
    fns=VDJdb_TRA_path,
    fn_blosum=None,
    antigen_ids=TCR_Predict_Target,
    blosum_encoding=False,
    is_train=True,
    chains="trb"
)

Found 0 CDR3 observations with unkown amino acids out of 8146.
Found 0 antigen observations with unkown amino acids out of 8146.
Found 0 CDR3+antigen observations with unkown amino acids out of 8146, leaving 8146 observations.
Assembled 8146 single-chain observations into 8146 multiple chain observations.


In [64]:
data = ffn.x_train
print(data.shape)
data = data.reshape(len(data),len(data[0][0][:])*len(data[0][0][0][:]))
#data = data.flatten()
target = VDJdb_TRA["Epitope"]
print(data.shape)
#print(data.reshape(25655,676))

(8146, 1, 24, 26)
(8146, 624)


In [17]:
# 1. load vdj dataset
import pandas as pd
import numpy as np
vdjdb_tra = pd.read_csv("data/Processed_TRA_Conf_by_GIANA.csv")
display(vdjdb_tra)

Unnamed: 0                      V1   V2             V3  \
0                CAASFSDGQKLLF           CAASFSDGQKLLF    1    TRAV13-1*01   
1              CAASFSDGQKLLF.1           CAASFSDGQKLLF    1    TRAV13-1*01   
2                CAASIGAGNMLTF           CAASIGAGNMLTF    2  TRAV29/DV5*01   
3              CAASIGAGNMLTF.1           CAASIGAGNMLTF    2  TRAV29/DV5*01   
4                CAASMNGDDKIIF           CAASMNGDDKIIF    3  TRAV23/DV6*01   
...                        ...                     ...  ...            ...   
1498      CLVGSPVPFSGGYNKLIF.1      CLVGSPVPFSGGYNKLIF  416       TRAV4*01   
1499       CAADTLLNAGGTSYGKLTF     CAADTLLNAGGTSYGKLTF  417    TRAV13-1*01   
1500     CAADTLLNAGGTSYGKLTF.1     CAADTLLNAGGTSYGKLTF  417    TRAV13-1*01   
1501    CAAIPVRNGRMNYGGSQGNLIF  CAAIPVRNGRMNYGGSQGNLIF  418  TRAV29/DV5*01   
1502  CAAIPVRNGRMNYGGSQGNLIF.1  CAAIPVRNGRMNYGGSQGNLIF  418  TRAV29/DV5*01   

             V4             V5          V6      V6.1        V7        V8  ...  \
0           NaN  PKYVKQNTLKLAT  InfluenzaA -0.131946 -0.122627  0.180292  ...   
1           NaN  PKYVKQNTLKLAT  InfluenzaA -0.131946 -0.122627  0.180292  ...   
2     TRAJ39*01      NLVPMVATV         CMV -0.330413 -0.438601 -0.550938  ...   
3     TRAJ39*01      NLVPMVATV         CMV -0.330413 -0.438601 -0.550938  ...   
4     TRAJ30*01  GMFNMLSTVLGVS  InfluenzaA -0.422125  0.122257  0.162796  ...   
...         ...            ...         ...       ...       ...       ...  ...   
1498   TRAJ4*01      NLVPMVATV         CMV -0.462359 -0.561227 -0.370646  ...   
1499  TRAJ52*01      NLVPMVATV         CMV  0.247162 -0.242762 -0.928951  ...   
1500  TRAJ52*01      NLVPMVATV         CMV  0.247162 -0.242762 -0.928951  ...   
1501  TRAJ42*01      GILGFVFTL  InfluenzaA -0.660825 -0.877201 -1.101875  ...   
1502  TRAJ42*01      GILGFVFTL  InfluenzaA -0.660825 -0.877201 -1.101875  ...   

           V92       V93       V94       V95       V96       V97       V98  \
0    -0.600459 -0.090567  0.221479 -0.330294  0.556356 -0.541500  0.054591   
1    -0.600459 -0.090567  0.221479 -0.330294  0.556356 -0.541500  0.054591   
2     0.027839  0.026379 -0.417603  0.218099  0.535328  0.048330  0.078777   
3     0.027839  0.026379 -0.417603  0.218099  0.535328  0.048330  0.078777   
4     0.534093  0.548508  0.594903  0.326693 -0.453553 -0.563170 -0.554163   
...        ...       ...       ...       ...       ...       ...       ...   
1498  1.221860  1.126777  0.535163  0.207328 -0.574577 -0.784084 -0.119884   
1499  0.208611 -0.173046 -0.782782  0.103752 -0.537859  0.720856 -0.197778   
1500  0.208611 -0.173046 -0.782782  0.103752 -0.537859  0.720856 -0.197778   
1501 -0.484122  0.395205 -0.749790  0.869585 -0.586457  0.291919 -0.971622   
1502 -0.484122  0.395205 -0.749790  0.869585 -0.586457  0.291919 -0.971622   

           V99      V100      V101  
0     0.573342 -0.062271  0.652999  
1     0.573342 -0.062271  0.652999  
2     0.504649 -0.269721 -0.524168  
3     0.504649 -0.269721 -0.524168  
4     0.181178 -0.716009 -0.089898  
...        ...       ...       ...  
1498  0.895657 -0.388549 -0.055234  
1499 -0.009423 -0.952306  0.570936  
1500 -0.009423 -0.952306  0.570936  
1501 -0.284567 -0.042783  0.375740  
1502 -0.284567 -0.042783  0.375740  

[1503 rows x 103 columns]

In [18]:
data=vdjdb_tra[['V1']]
target=vdjdb_tra['V5']
# 3. feature engineering

# 3.1 feature extraction

# 1) Dictionary feature extraction
from sklearn.feature_extraction import DictVectorizer
data=data.to_dict(orient="records") 
DicVec_transfer = DictVectorizer(sparse=False)
data = DicVec_transfer.fit_transform(data)
print("Dictionary feature extraction return:\n", data)
print("DictVectorized feature names：\n", DicVec_transfer.get_feature_names_out())

Dictionary feature extraction return:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DictVectorized feature names：
 ['V1=CAAAASGGSYIPTF' 'V1=CAAALNTNAGKSTF' 'V1=CAAAMDSSYKLIF'
 'V1=CAAASSGGSYIPTF' 'V1=CAADNQGGKLIF' 'V1=CAADTLLNAGGTSYGKLTF'
 'V1=CAAEDNTDKLIF' 'V1=CAAENQGGKLIF' 'V1=CAAGGGSYIPTF' 'V1=CAAGGSQGNLIF'
 'V1=CAAILADYKLSF' 'V1=CAAIPVRNGRMNYGGSQGNLIF' 'V1=CAAITGIGGSQGNLIF'
 'V1=CAAKGGSEKLVF' 'V1=CAAKTGGGNKLTF' 'V1=CAALIQGAQKLVF'
 'V1=CAALITQGGSEKLVF' 'V1=CAANNAGNNRKLIW' 'V1=CAANYGGSQGNLIF'
 'V1=CAAPGNYGQNFVF' 'V1=CAAPLYSGGGADGLTF' 'V1=CAAPTGFGNEKLTF'
 'V1=CAAPYSGGSNYKLTF' 'V1=CAAQGSQGNLIF' 'V1=CAAQRANRDDKIIF'
 'V1=CAARANDYKLSF' 'V1=CAARGIGSGTYKYIF' 'V1=CAARSNDYKLSF'
 'V1=CAARVQGGSEKLVF' 'V1=CAASAANFGNEKLSF' 'V1=CAASAANFGNEKLTF'
 'V1=CAASAGGGSQGNLIF' 'V1=CAASAGSYNSDKLIF' 'V1=CAASAGSYNTDKLIF'
 'V1=CAASAPAAGNKLTF' 'V1=CAASDQTGANNLFF' 'V1=CAASETSYDKVIF'
 'V1=CAASFAGNTPLVF' 'V

In [19]:
vdjdb_tra = pd.read_csv("data/Processed_TRA_by_GIANA.csv")
vdjdb_tra.head()

Unnamed: 0             V1  V2             V3         V4          V5  \
0    CAAGWVSQGNLIF  CAAGWVSQGNLIF   1     TRAV1-1*01  TRAJ42*01   KLGGALQAK   
1  CAAGWVSQGNLIF.1  CAAGWVSQGNLIF   1     TRAV1-1*01  TRAJ42*01   RLRAEAQVK   
2    CAARVTAGTALIF  CAARVTAGTALIF   2    TRAV13-1*01  TRAJ15*01   RLRAEAQVK   
3  CAARVTAGTALIF.1  CAARVTAGTALIF   2    TRAV13-1*01  TRAJ15*01   KLGGALQAK   
4    CAASAGVDDKIIF  CAASAGVDDKIIF   3  TRAV29/DV5*01  TRAJ30*01  AVFDRKSDAK   

    V6      V6.1        V7        V8  ...       V92       V93       V94  \
0  CMV  0.685463  0.225814 -0.325718  ...  0.161617  0.083978  0.091194   
1  EBV  0.685463  0.225814 -0.325718  ...  0.161617  0.083978  0.091194   
2  EBV  0.408501 -0.463889 -0.397330  ...  0.027839  0.026379 -0.417603   
3  CMV  0.408501 -0.463889 -0.397330  ...  0.027839  0.026379 -0.417603   
4  EBV -0.330413 -0.438601 -0.550938  ...  0.047840 -0.530679 -0.500499   

        V95       V96       V97       V98       V99      V100      V101  
0  0.345470 -0.294153  0.298919 -0.608347  0.594359 -0.294738  0.486415  
1  0.345470 -0.294153  0.298919 -0.608347  0.594359 -0.294738  0.486415  
2  0.218099  0.535328  0.048330  0.078777  0.504649 -0.269721 -0.524168  
3  0.218099  0.535328  0.048330  0.078777  0.504649 -0.269721 -0.524168  
4  0.368742  0.224292  0.461648  0.111592 -0.268280 -0.393728 -0.409874  

[5 rows x 103 columns]

In [20]:
data=vdjdb_tra[['V1']]
target=vdjdb_tra['V5']
# 3. feature engineering

# 3.1 feature extraction

# 1) Dictionary feature extraction
from sklearn.feature_extraction import DictVectorizer
data=data.to_dict(orient="records") 
DicVec_transfer = DictVectorizer(sparse=False)
data = DicVec_transfer.fit_transform(data)
print("Dictionary feature extraction return:\n", data)
print("DictVectorized feature names：\n", DicVec_transfer.get_feature_names_out())

Dictionary feature extraction return:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DictVectorized feature names：
 ['V1=CAAAASGGSYIPTF' 'V1=CAAADDKIIF' 'V1=CAAADNYGQNFVF' ...
 'V1=SLSGGSQGNLLF' 'V1=WATSGANNLFF' 'V1=YFLSSGARVTGGGNKITF']


In [71]:
data=vdjdb_tra[['TRA_CDR3']]
target=vdjdb_tra['TCR_name']
# 3. feature engineering

# 3.1 feature extraction

# 1) Dictionary feature extraction
from sklearn.feature_extraction import DictVectorizer
data=data.to_dict(orient="records") 
DicVec_transfer = DictVectorizer(sparse=False)
data = DicVec_transfer.fit_transform(data)
print("Dictionary feature extraction return:\n", data)
print("DictVectorized feature names：\n", DicVec_transfer.get_feature_names_out())

Dictionary feature extraction return:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DictVectorized feature names：
 ['TRA_CDR3=CAAAASGGSYIPTF' 'TRA_CDR3=CAAAMDSSYKLIF'
 'TRA_CDR3=CAADNQGGKLIF' ... 'TRA_CDR3=CWSPFGNEKLTF'
 'TRA_CDR3=CWSPNQAGTALIF' 'TRA_CDR3=SSGNQFYF']


In [65]:
# 2. split dataset
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, target,
random_state=22)
print("x_train:\n", x_train.shape)
print("x_test:\n", x_test.shape)

x_train:
 (6109, 624)
x_test:
 (2037, 624)


In [46]:
# 2) Text feature extraction
#from sklearn.feature_extraction.text import CountVectorizer
#CountVec_transfer = CountVectorizer()
#**data** = CountVec_transfer.fit_transform(**data**)\
#print("Text feature extraction return:\n", **data**)
#print("CountVectorized feature names：\n", CountVec_transfer.get_feature_names())

In [40]:
# 3) Tf-idf feature extraction
#from sklearn.feature_extraction.text import TfidfVectorizer
#Tfidf_transfer = TfidfVectorizer(stop_words=[**])
#**data** = Tfidf_transfer.fit_transform(**data**)\
#print("Tf-idf return:\n", **data**)
#print("Tf-idf feature names：\n", Tfidf_transfer.get_feature_names())

In [6]:
# 3.2 feture preprocessing

# 1) MinMaxScaler
#from sklearn.preprocessing import MinMaxScaler

#MMS_transfer = MinMaxScaler(feature_range=(0, 1))
#**data** = MMS_transfer.fit_transform(**data**)\
#print("Tf-idf return:\n", **data**)

In [7]:
# 2) StandardScaler
#from sklearn.preprocessing import StandardScaler

#SS_transfer = StandardScaler()
#**data** = SS_transfer.fit_transform(**data**)\
#print("Tf-idf return:\n", **data**)
#print("feature mean：\n", SS_transfer.mean_)
#print("feature variance：\n", SS_transfer.var_)

In [8]:
# 3.3 Dimentionality reduction

# 1) Variance filter
#from sklearn.feature_selection import VarianceThreshold
#VT_transfer = VarianceThreshold(threshold=**1**)
#**data** = VT_transfer.fit_transform(**data.iloc[:, 1:10]**)
#print("VarianceThreshold return:\n", **data**)
#print("shape：\n", Tfidf_transfer.get_feature_names())

In [9]:
# 2) Pearson Correlation Coefficient filter
#from scipy.stats import pearsonr
#for i in range(len(**factor**)):
#    for j in range(i, len(**factor**) - 1):
#        print("指标%s与指标%s之间的相关性大小为%f" % (**factor**[i], **factor**[j + 1],pearsonr(**data**[**factor**[i]], **data**[**factor**[j + 1]])[0]))

In [10]:
# import matplotlib.pyplot as plt
# plt.figure(figsize=(**20, 8**), dpi=**100**)
# plt.scatter(**data['revenue']**, **data['total_expense']**)
# plt.show()

In [108]:
# 3) PCA
from sklearn.decomposition import PCA
PCA_transfer = PCA(n_components=0.9)
x_train_PCA = PCA_transfer.fit_transform(x_train)
x_test_PCA = PCA_transfer.transform(x_test)
print("PCA return:\n", x_train_PCA)

PCA return:
 [[ 0.29081808 -0.49469335  0.38898774 ...  0.04274532  0.10520099
  -0.08253806]
 [-1.1728663   0.92048471 -0.76192402 ... -0.02281943  0.01603935
  -0.05895997]
 [-0.49751789 -0.12475446  0.41604051 ... -0.10943265 -0.1094704
   0.00214134]
 ...
 [ 1.10112946  0.82922955  0.41095325 ...  0.20089738 -0.16155902
  -0.01970484]
 [-1.26661637  0.43584152 -0.26129593 ...  0.04353368 -0.25321802
  -0.24163461]
 [-1.28354896  0.53669497 -0.44085026 ...  0.08666802  0.2463859
  -0.0254109 ]]


In [66]:
# 4. Algorithm prediction

# 1) KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=12)
knn.fit(x_train, y_train)
y_predict = knn.predict(x_test)
print("predict test set：", y_predict)
print("accuracy：", knn.score(x_test, y_test))

predict test set： ['GILGFVFTL' 'KLGGALQAK' 'GILGFVFTL' ... 'KLGGALQAK' 'FTSDYYQLY'
 'KLGGALQAK']
accuracy： 0.5400098183603338


In [20]:
# 4. Algorithm prediction

# 1) KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=14)
knn.fit(x_train_PCA, y_train)
y_predict = knn.predict(x_test_PCA)
print("predict test set：", y_predict)
print("accuracy：", knn.score(x_test_PCA, y_test))

NameError: name 'x_train_PCA' is not defined

In [67]:
# Grid Search & cross validation
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier()
param = {"n_neighbors": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}
gc = GridSearchCV(knn, param_grid=param, cv=2)
gc.fit(x_train, y_train)
print("Accuracy：", gc.score(x_test, y_test))
# 训练验证集的结果
print("Best results in cross validation：", gc.best_score_)
print("k value chosen by gc：", gc.best_estimator_)
print("cross validation results：", gc.cv_results_)

D:\Anaconda Python\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Accuracy： 0.5400098183603338
Best results in cross validation： 0.5229995916385584
k value chosen by gc： KNeighborsClassifier(n_neighbors=19)
cross validation results： {'mean_fit_time': array([0.02123666, 0.02495193, 0.02791286, 0.0164392 , 0.0162183 ,
       0.01495481, 0.01645613, 0.01595771, 0.01548123, 0.01644099,
       0.01599133, 0.01595116, 0.01596129, 0.01545894, 0.01545846,
       0.01496148, 0.01545751, 0.01495647, 0.01545906, 0.01598704]), 'std_fit_time': array([1.20806694e-03, 8.99457932e-03, 1.19473934e-02, 5.60998917e-04,
       2.52127647e-04, 5.24520874e-06, 4.82082367e-04, 3.57627869e-07,
       4.75168228e-04, 4.98652458e-04, 3.32593918e-05, 9.91344452e-04,
       9.17911530e-06, 4.99129295e-04, 4.98652458e-04, 1.02519989e-05,
       4.97698784e-04, 3.33786011e-06, 4.98294830e-04, 5.60283661e-06]), 'mean_score_time': array([0.21266305, 0.23661613, 0.222188  , 0.19853115, 0.19580317,
       0.19786596, 0.19783509, 0.19486856, 0.19793594, 0.19982171,
       0.19624627, 

In [23]:
# 3.2 feture preprocessing

# 1) MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

MMS_transfer = MinMaxScaler(feature_range=(0, 1))
x_train_PCA_MMS = MMS_transfer.fit_transform(x_train_PCA)
x_test_PCA_MMS = MMS_transfer.transform(x_test_PCA)
print("Tf-idf return:\n", x_train_PCA_MMS)

NameError: name 'x_train_PCA' is not defined

In [24]:
# 2)Naive Bayes
from sklearn.naive_bayes import MultinomialNB
mlb = MultinomialNB(alpha=1.0)
mlb.fit(x_train, y_train)
y_predict = mlb.predict(x_test)
print("Prediction：", y_predict)
print("Real category：", y_test)
print("Accuracy：", mlb.score(x_test, y_test))

Prediction： ['NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL'
 'NLVPMVATV' 'NCTFEYVSQPFLMDL' 'NLVPMVATV' 'NLVPMVATV' 'CINGVCWTV'
 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'GLCTLVAML' 'NLVPMVATV'
 'GILGFVFTL' 'NLVPMVATV' 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL' 'NCTFEYVSQPFLMDL' 'NLVPMVATV'
 'GILGFVFTL' 'NLVPMVATV' 'GILGFVFTL' 'GLCTLVAML' 'GLCTLVAML' 'NLVPMVATV'
 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL' 'NLVPMVATV'
 'NLVPMVATV' 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'GILGFVFTL' 'GILGFVFTL' 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'NLVPMVATV' 'NLVPMVATV' 'GLCTLVAML' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'NLVPMVATV' 'GILGFVFTL' 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL'
 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'GLCTLVAML' 'NLVPMVATV'
 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'N

In [68]:
# 3) Decision Tree
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier(max_depth=5,criterion='gini')
dc.fit(x_train, y_train)
print("Accuracy：", dc.score(x_test, y_test))

Accuracy： 0.24129353233830847


In [68]:
# 4) Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param = {"n_estimators": [120,200,300,500,800,1200], "max_depth": [5, 8, 15, 25, 30]}
gc = GridSearchCV(rf, param_grid=param, cv=2)
gc.fit(x_train, y_train)
print("Accuracy：", gc.score(x_test, y_test))

D:\Anaconda Python\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Accuracy： 0.6057928325969563


In [18]:
# 5. Regression

# 1) Linear regression
#from sklearn.linear_model import LinearRegression
#lr = LinearRegression()
#lr.fit(x_train, y_train)
#y_lr_predict = std_y.inverse_transform(lr.predict(x_test))
#print(lr.coef_)
#print("Linear regression Prediction：", y_lr_predict)
#print("Linear regression MSE：", mean_squared_error(y_test, y_lr_predict))

In [19]:
# 2) Gradient Descent Regression
#from sklearn.linear_model import SGDRegressor
#sgd = SGDRegressor(learning_rate='constant', eta0=0.001)
#sgd.fit(x_train, y_train)
#print("SGD params：", sgd.coef_)
#y_sgd_predict = std_y.inverse_transform(sgd.predict(x_test))
#print("SGD Prediction：", y_sgd_predict)
#print("SGD MSE：", mean_squared_error(y_test, y_sgd_predict))

In [20]:
# 3) Ridge Regression
#from sklearn.linear_model import Ridge
#from sklearn.linear_model import RidgeCV
#rd = Ridge(alpha=1.0)
#rd.fit(x_train, y_train)
#y_rd_predict = std_y.inverse_transform(rd.predict(x_test))
#print("Ridge Prediction：", y_rd_predict)
#print("Ridge MSE：", mean_squared_error(y_test, y_rd_predict))

In [47]:
# 4) Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
print("lr params：", lr.coef_)
# 预测类别
print("lr prediction：", lr.predict(x_test))
# 得出准确率
print("lr accuracy:", lr.score(x_test, y_test))

lr params： [[ 0.          0.          0.         ...  0.          0.
  -0.0015607 ]
 [ 0.          0.          0.         ...  0.          0.
   0.00996796]
 [ 0.          0.          0.         ...  0.          0.
  -0.00783945]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.00072257]
 [ 0.          0.          0.         ...  0.          0.
   0.00023593]
 [ 0.          0.          0.         ...  0.          0.
  -0.00551341]]
lr prediction： ['KLVALGINAV' 'NLVPMVATV' 'ITDQVPFSV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'KLFEFLVYGV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'GILGFVFTL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL' 'GLCTLVAML'
 'NLVPMVATV' 'NLVPMVATV' 'LPEPLPQGQLTAY' 'NLVPMVATV' 'NLVPMVATV'
 'GILGFVFTL' 'NLVPMVATV' 'KLEQLDWTV' 'GILGFVFTL' 'GILGFVFTL'
 'NCTFEYVSQPFLMDL' 'LPEPLPQGQLTAY' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV'
 'LMDYWQGQL' 'NLVPMVATV' 'NLVPMVATV' 'NLVPMVATV' 'GILGFVFTL' 'FLKETGGL'
 'SLLMWITQC' 'GILGFVFTL' 'NLVPMVATV' 'GI

D:\Anaconda Python\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [48]:
# Assessment

# 1) precision & recall
from sklearn.metrics import classification_report
print("Precision & Recall：", classification_report(y_test, lr.predict(x_test)))

Precision & Recall：                   precision    recall  f1-score   support

       AAGIGILTV       0.00      0.00      0.00         1
      ALDPHSGHFV       1.00      1.00      1.00         1
       ALSPVIPHI       1.00      1.00      1.00         1
      ALWGPDPAAA       0.00      0.00      0.00         0
  DFHFEVFNFVPCSI       1.00      1.00      1.00         3
      EAAGIGILTV       1.00      1.00      1.00         1
      ELAGIGALTV       0.00      0.00      0.00         1
      ELAGIGILTV       0.50      0.25      0.33         4
       EMMLFDWKV       0.00      0.00      0.00         1
  ENPVVHFFKNIVTP       0.00      0.00      0.00         1
     EPLPQGQLTAY       1.00      1.00      1.00         1
        FLKEKGGL       0.00      0.00      0.00         1
        FLKEMGGL       0.00      0.00      0.00         0
        FLKEQGGL       0.00      0.00      0.00         1
        FLKETGGL       0.00      0.00      0.00         0
       FLRGRAYGL       1.00      1.00      1.00    

D:\Anaconda Python\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda Python\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda Python\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Anaconda Python\lib\site-packages\sklearn\metrics\_classification.py:1344: Und

In [23]:
# 2) AUC
#from sklearn.metrics import roc_auc_score
#print("AUC：", roc_auc_score(y_test, lr.predict(x_test)))

In [24]:
# ** model import & export
#from sklearn.externals import joblib
#joblib.dump(**lr**, **"test.pkl"**)
#model = joblib.load(**"test.pkl"**)

In [25]:
# 6. Unsupervised Cluster

# 1) K-means
from sklearn.cluster import KMeans
km = KMeans(n_clusters=33)
km.fit(data)
pre = km.predict(data)

E:\Programs\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [26]:
# Assessment
from sklearn.metrics import silhouette_score
silhouette_score(data, pre)

0.08070106594394624