In [1]:
# 1. load vdj dataset
import pandas as pd
import numpy as np
vdjdb = pd.read_csv("../processed_data/vdjdb_preprocessd_nonull.txt", sep = "\t")
vdjdb.head()

complex.id gene                  cdr3       v.segm      j.segm  \
0           1  TRA         CIVRAPGRADMRF  TRAV26-1*01   TRAJ43*01   
1           1  TRB  CASSYLPGQGDHYSNQPQHF    TRBV13*01  TRBJ1-5*01   
2           0  TRB   CASSFEAGQGFFSNQPQHF    TRBV13*01  TRBJ1-5*01   
3           2  TRA        CAVPSGAGSYQLTF    TRAV20*01   TRAJ28*01   
4           2  TRB   CASSFEPGQGFYSNQPQHF    TRBV13*01  TRBJ1-5*01   

       species     mhc.a mhc.b mhc.class antigen.epitope antigen.gene  \
0  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
1  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
2  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
3  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   
4  HomoSapiens  HLA-B*08   B2M      MHCI        FLKEKGGL          Nef   

  antigen.species  vdjdb.score  
0           HIV-1            2  
1           HIV-1            2  
2           HIV-1            2  
3           HIV-1            2  
4           HIV-1            2

In [2]:
data=vdjdb[['gene','cdr3','v.segm','j.segm','mhc.a','mhc.b']]
target=vdjdb['antigen.epitope']
# 3. feature engineering

# 3.1 feature extraction

# 1) Dictionary feature extraction
from sklearn.feature_extraction import DictVectorizer
data=data.to_dict(orient="records") 
DicVec_transfer = DictVectorizer(sparse=False)
data = DicVec_transfer.fit_transform(data)
print("Dictionary feature extraction return:\n", data)
print("DictVectorized feature names：\n", DicVec_transfer.get_feature_names_out())

Dictionary feature extraction return:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
DictVectorized feature names：
 ['cdr3=CAAAASGGSYIPTF' 'cdr3=CAAADEEIGNQPQHF' 'cdr3=CAAALNTNAGKSTF' ...
 'v.segm=TRBV7-9*03' 'v.segm=TRBV9*01' 'v.segm=TRBV9*02']


In [3]:
# 2. split dataset
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, target,
random_state=22)
print("x_train:\n", x_train.shape)
print("x_test:\n", x_test.shape)

x_train:
 (8498, 7445)
x_test:
 (2833, 7445)


In [4]:
# 2) Text feature extraction
#from sklearn.feature_extraction.text import CountVectorizer
#CountVec_transfer = CountVectorizer()
#**data** = CountVec_transfer.fit_transform(**data**)\
#print("Text feature extraction return:\n", **data**)
#print("CountVectorized feature names：\n", CountVec_transfer.get_feature_names())

In [5]:
# 3) Tf-idf feature extraction
#from sklearn.feature_extraction.text import TfidfVectorizer
#Tfidf_transfer = TfidfVectorizer(stop_words=[**])
#**data** = Tfidf_transfer.fit_transform(**data**)\
#print("Tf-idf return:\n", **data**)
#print("Tf-idf feature names：\n", Tfidf_transfer.get_feature_names())

In [6]:
# 3.2 feture preprocessing

# 1) MinMaxScaler
#from sklearn.preprocessing import MinMaxScaler

#MMS_transfer = MinMaxScaler(feature_range=(0, 1))
#**data** = MMS_transfer.fit_transform(**data**)\
#print("Tf-idf return:\n", **data**)

In [7]:
# 2) StandardScaler
#from sklearn.preprocessing import StandardScaler

#SS_transfer = StandardScaler()
#**data** = SS_transfer.fit_transform(**data**)\
#print("Tf-idf return:\n", **data**)
#print("feature mean：\n", SS_transfer.mean_)
#print("feature variance：\n", SS_transfer.var_)

In [8]:
# 3.3 Dimentionality reduction

# 1) Variance filter
#from sklearn.feature_selection import VarianceThreshold
#VT_transfer = VarianceThreshold(threshold=**1**)
#**data** = VT_transfer.fit_transform(**data.iloc[:, 1:10]**)
#print("VarianceThreshold return:\n", **data**)
#print("shape：\n", Tfidf_transfer.get_feature_names())

In [9]:
# 2) Pearson Correlation Coefficient filter
#from scipy.stats import pearsonr
#for i in range(len(**factor**)):
#    for j in range(i, len(**factor**) - 1):
#        print("指标%s与指标%s之间的相关性大小为%f" % (**factor**[i], **factor**[j + 1],pearsonr(**data**[**factor**[i]], **data**[**factor**[j + 1]])[0]))

In [10]:
# import matplotlib.pyplot as plt
# plt.figure(figsize=(**20, 8**), dpi=**100**)
# plt.scatter(**data['revenue']**, **data['total_expense']**)
# plt.show()

In [11]:
# 3) PCA
from sklearn.decomposition import PCA
PCA_transfer = PCA(n_components=0.9)
x_train_PCA = PCA_transfer.fit_transform(x_train)
x_test_PCA = PCA_transfer.transform(x_test)
print("PCA return:\n", x_train_PCA)

PCA return:
 [[-5.04220668e-01 -2.24683873e-01 -2.13460898e-01 ...  3.69968263e-04
   2.09694094e-04  5.43639057e-04]
 [-3.46380135e-01 -2.74192862e-01 -8.40800538e-03 ...  2.19233115e-03
   1.66501252e-03  5.45340397e-04]
 [ 1.01849689e+00 -2.13872723e-01  4.18591183e-03 ... -1.81061763e-17
  -4.58888570e-17 -1.70931249e-18]
 ...
 [-4.37203687e-01 -8.75713066e-02  4.60658160e-02 ... -4.68005624e-03
   4.19321522e-03 -1.88402822e-02]
 [ 1.05974338e+00  7.51370275e-01 -2.03618296e-02 ... -2.60208521e-17
  -3.05745013e-17 -2.24158799e-17]
 [ 1.02911474e+00  7.24982219e-01 -1.47002379e-02 ...  4.09378675e-05
  -4.97881132e-03  9.25093545e-03]]


In [12]:
# 4. Algorithm prediction

# 1) KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)
y_predict = knn.predict(x_test)
print("predict test set：", y_predict)
print("accuracy：", knn.score(x_test, y_test))

predict test set： ['GPGHKARVL' 'GILGFVFTL' 'SSPPMFRV' ... 'FRDYVDRFYKTLRAEQASQE' 'GILGFVFTL'
 'FLRGRAYGL']
accuracy： 0.6579597599717614


In [13]:
# Grid Search & cross validation
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier()
param = {"n_neighbors": [3, 5, 10]}
gc = GridSearchCV(knn, param_grid=param, cv=2)
gc.fit(x_train, y_train)
print("Accuracy：", gc.score(x_test, y_test))
# 训练验证集的结果
print("Best results in cross validation：", gc.best_score_)
print("k value chosen by gc：", gc.best_estimator_)
print("cross validation results：", gc.cv_results_)

E:\Programs\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Accuracy： 0.6141899046946699
Best results in cross validation： 0.5582489997646505
k value chosen by gc： KNeighborsClassifier(n_neighbors=3)
cross validation results： {'mean_fit_time': array([0.12472558, 0.13429105, 0.13253713]), 'std_fit_time': array([0.00150943, 0.00708187, 0.00607657]), 'mean_score_time': array([1.48383343, 1.50972593, 1.58297765]), 'std_score_time': array([0.04057872, 0.00626123, 0.03334391]), 'param_n_neighbors': masked_array(data=[3, 5, 10],
             mask=[False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 10}], 'split0_test_score': array([0.55660155, 0.55048247, 0.55377736]), 'split1_test_score': array([0.55989645, 0.56554483, 0.55660155]), 'mean_test_score': array([0.558249  , 0.55801365, 0.55518946]), 'std_test_score': array([0.00164745, 0.00753118, 0.0014121 ]), 'rank_test_score': array([1, 2, 3])}


In [14]:
# 3.2 feture preprocessing

# 1) MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

MMS_transfer = MinMaxScaler(feature_range=(0, 1))
x_train_PCA_MMS = MMS_transfer.fit_transform(x_train_PCA)
x_test_PCA_MMS = MMS_transfer.transform(x_test_PCA)
print("Tf-idf return:\n", x_train_PCA_MMS)

Tf-idf return:
 [[0.06585528 0.22238599 0.32722003 ... 0.48827826 0.41081152 0.40098575]
 [0.1541024  0.1897655  0.41899183 ... 0.50017994 0.41900088 0.40099663]
 [0.91719197 0.22950924 0.42462826 ... 0.48586203 0.40963153 0.39751074]
 ...
 [0.10332382 0.31272675 0.44337169 ... 0.45529702 0.43322758 0.27708121]
 [0.94025248 0.86548877 0.41364187 ... 0.48586203 0.40963153 0.39751074]
 [0.9231283  0.8481022  0.41617573 ... 0.48612939 0.38161477 0.45664392]]


In [15]:
# 2)Naive Bayes
from sklearn.naive_bayes import MultinomialNB
mlb = MultinomialNB(alpha=1.0)
mlb.fit(x_train, y_train)
y_predict = mlb.predict(x_test)
print("Prediction：", y_predict)
print("Real category：", y_test)
print("Accuracy：", mlb.score(x_test, y_test))

Prediction： ['TPRVTGGGAM' 'GILGFVFTL' 'SSPPMFRV' ... 'FRDYVDRFYKTLRAEQASQE'
 'NLVPMVATV' 'NLVPMVATV']
Real category： 3214                GPGHKARVL
5359                GILGFVFTL
6153                 SSPPMFRV
8980                ATDALMTGY
3030                NLVPMVATV
                 ...         
10466               CTPYDINQM
2008                NLVPMVATV
9588     FRDYVDRFYKTLRAEQASQE
3892                GILGFVFTL
9815                FLRGRAYGL
Name: antigen.epitope, Length: 2833, dtype: object
Accuracy： 0.4525238263325097


In [16]:
# 3) Decision Tree
from sklearn.tree import DecisionTreeClassifier
dc = DecisionTreeClassifier(max_depth=5,criterion='gini')
dc.fit(x_train, y_train)
print("Accuracy：", dc.score(x_test, y_test))

Accuracy： 0.3042710907165549


In [17]:
# 4) Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
param = {"n_estimators": [120,200,300,500,800,1200], "max_depth": [5, 8, 15, 25,
30]}
gc = GridSearchCV(rf, param_grid=param, cv=2)
gc.fit(x_train, y_train)
print("Accuracy：", gc.score(x_test, y_test))

E:\Programs\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Accuracy： 0.6131309565831274


In [18]:
# 5. Regression

# 1) Linear regression
#from sklearn.linear_model import LinearRegression
#lr = LinearRegression()
#lr.fit(x_train, y_train)
#y_lr_predict = std_y.inverse_transform(lr.predict(x_test))
#print(lr.coef_)
#print("Linear regression Prediction：", y_lr_predict)
#print("Linear regression MSE：", mean_squared_error(y_test, y_lr_predict))

In [19]:
# 2) Gradient Descent Regression
#from sklearn.linear_model import SGDRegressor
#sgd = SGDRegressor(learning_rate='constant', eta0=0.001)
#sgd.fit(x_train, y_train)
#print("SGD params：", sgd.coef_)
#y_sgd_predict = std_y.inverse_transform(sgd.predict(x_test))
#print("SGD Prediction：", y_sgd_predict)
#print("SGD MSE：", mean_squared_error(y_test, y_sgd_predict))

In [20]:
# 3) Ridge Regression
#from sklearn.linear_model import Ridge
#from sklearn.linear_model import RidgeCV
#rd = Ridge(alpha=1.0)
#rd.fit(x_train, y_train)
#y_rd_predict = std_y.inverse_transform(rd.predict(x_test))
#print("Ridge Prediction：", y_rd_predict)
#print("Ridge MSE：", mean_squared_error(y_test, y_rd_predict))

In [21]:
# 4) Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
print("lr params：", lr.coef_)
# 预测类别
print("lr prediction：", lr.predict(x_test))
# 得出准确率
print("lr accuracy:", lr.score(x_test, y_test))

E:\Programs\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


lr params： [[-2.95618107e-04 -1.73112652e-04 -1.15104269e-03 ... -4.83755904e-03
  -2.02738952e-01 -2.88014688e-04]
 [-2.53902233e-04 -1.01580103e-03 -2.82280548e-03 ... -8.50861425e-03
  -1.62232948e-01 -3.12062026e-03]
 [-1.11021432e-04 -2.21046804e-05 -3.05674873e-03 ... -8.28382441e-04
  -2.48808878e-02 -9.57077346e-05]
 ...
 [-2.33369110e-05 -1.47951525e-04 -1.21189234e-04 ... -3.28393387e-02
  -7.15737609e-01 -3.54023008e-02]
 [-3.56185530e-05 -2.90561696e-05 -4.20072555e-04 ... -1.10528005e-03
  -3.47703304e-02 -1.32037817e-04]
 [-1.37214452e-04 -4.73808388e-05 -6.71975239e-04 ... -1.73973492e-03
   8.21178112e-01 -1.81561584e-04]]
lr prediction： ['TPRVTGGGAM' 'GILGFVFTL' 'SSPPMFRV' ... 'FRDYVDRFYKTLRAEQASQE'
 'GILGFVFTL' 'FLRGRAYGL']
lr accuracy: 0.6696081891987292


In [22]:
# Assessment

# 1) precision & recall
from sklearn.metrics import classification_report
print("Precision & Recall：", classification_report(y_test, lr.predict(x_test)))

Precision & Recall：                           precision    recall  f1-score   support

               AAFKRSCLK       0.33      0.50      0.40         2
               AAGIGILTV       0.25      0.33      0.29         3
         AALALLLLDRLNQLE       0.00      0.00      0.00         1
          ADGLAYFRSSFKGG       0.00      0.00      0.00         0
           ADLIAYLEQATKG       0.00      0.00      0.00         1
           ADLIAYLKQATKG       0.00      0.00      0.00         1
              ALDPHSGHFV       0.00      0.00      0.00         3
               ALGIGILTV       0.00      0.00      0.00         1
               ALHGGWTTK       0.00      0.00      0.00         1
               ALLLQLFTL       0.00      0.00      0.00         1
               ALLPGLPAA       0.00      0.00      0.00         3
               ALSKGVHFV       0.00      0.00      0.00         3
               ALSPVIPHI       1.00      1.00      1.00         4
               ALTPVVVTL       0.00      0.00      0.00

E:\Programs\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\Programs\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\Programs\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\Programs\anaconda3\lib\site-packages\sklearn\metrics\_classification.

In [23]:
# 2) AUC
#from sklearn.metrics import roc_auc_score
#print("AUC：", roc_auc_score(y_test, lr.predict(x_test)))

In [24]:
# ** model import & export
#from sklearn.externals import joblib
#joblib.dump(**lr**, **"test.pkl"**)
#model = joblib.load(**"test.pkl"**)

In [25]:
# 6. Unsupervised Cluster

# 1) K-means
from sklearn.cluster import KMeans
km = KMeans(n_clusters=33)
km.fit(data)
pre = km.predict(data)

E:\Programs\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [26]:
# Assessment
from sklearn.metrics import silhouette_score
silhouette_score(data, pre)

0.08070106594394624