In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import tcellmatch.api as tm
import os

In [2]:
VDJdb_TRA_path = "D:\Master in UoB\TB2 of UoB\Mini Project\Mini-Project Development\TCRdist3\VDJdb_TRA.tsv"
VDJdb_TRA = pd.read_table("VDJdb_TRA.tsv")
display(VDJdb_TRA)

VDJdb_TRA_Train = VDJdb_TRA.sample(frac=0.6)
#display(VDJdb_TRA_Train)
VDJdb_TRA_Test = VDJdb_TRA.drop(VDJdb_TRA_Train.index)
#display(VDJdb_TRA_Test)
VDJdb_TRA_Train.to_csv("Train_Test_data/VDJdb_TRA_Train.tsv", sep='\t')
VDJdb_TRA_Test.to_csv("Train_Test_data/VDJdb_TRA_Test.tsv", sep='\t')
display(VDJdb_TRA_Test)

VDJdb_TRA_Train_path = "Train_Test_data/VDJdb_TRA_Train.tsv"
VDJdb_TRA_Test_path = "Train_Test_data/VDJdb_TRA_Test.tsv"

complex.id Gene              CDR3                V          J  \
0               1  TRA     CIVRAPGRADMRF      TRAV26-1*01  TRAJ43*01   
1               2  TRA    CAVPSGAGSYQLTF        TRAV20*01  TRAJ28*01   
2               4  TRA     CAYRPPGTYKYIF  TRAV38-2/DV8*01  TRAJ40*01   
3               5  TRA     CIVRAPGRADMRF      TRAV26-1*01  TRAJ43*01   
4               6  TRA    CAVPSGAGSYQLTF        TRAV20*01  TRAJ28*01   
...           ...  ...               ...              ...        ...   
25650       29262  TRA  CAFLNAGGTSYGKLTF      TRAV38-1*01  TRAJ52*01   
25651       29263  TRA      CAVYNQGGKLIF       TRAV8-1*01  TRAJ23*01   
25652       29264  TRA    CAVRALYNFNKFYF         TRAV3*01  TRAJ21*01   
25653       29265  TRA     CAVESYNTDKLIF        TRAV41*01  TRAJ34*01   
25654       29266  TRA  CAMREGQGNAGNMLTF    TRAV14/DV4*01  TRAJ39*01   

           Species        MHC A MHC B MHC class    Epitope Epitope gene  \
0      HomoSapiens     HLA-B*08   B2M      MHCI   FLKEKGGL          Nef   
1      HomoSapiens     HLA-B*08   B2M      MHCI   FLKEKGGL          Nef   
2      HomoSapiens     HLA-B*08   B2M      MHCI   FLKEKGGL          Nef   
3      HomoSapiens     HLA-B*08   B2M      MHCI   FLKEQGGL          Nef   
4      HomoSapiens     HLA-B*08   B2M      MHCI   FLKEQGGL          Nef   
...            ...          ...   ...       ...        ...          ...   
25650  HomoSapiens  HLA-A*24:01   B2M      MHCI  QYIKWPWYI        Spike   
25651  HomoSapiens  HLA-A*24:01   B2M      MHCI  QYIKWPWYI        Spike   
25652  HomoSapiens  HLA-A*24:01   B2M      MHCI  QYIKWPWYI        Spike   
25653  HomoSapiens  HLA-A*24:01   B2M      MHCI  QYIKWPWYI        Spike   
25654  HomoSapiens  HLA-A*24:01   B2M      MHCI  QYIKWPWYI        Spike   

      Epitope species      Reference  \
0               HIV-1  PMID:15596521   
1               HIV-1  PMID:15596521   
2               HIV-1  PMID:15596521   
3               HIV-1  PMID:15596521   
4               HIV-1  PMID:15596521   
...               ...            ...   
25650      SARS-CoV-2  PMID:34086357   
25651      SARS-CoV-2  PMID:34086357   
25652      SARS-CoV-2  PMID:34086357   
25653      SARS-CoV-2  PMID:34086357   
25654      SARS-CoV-2  PMID:34086357   

                                                  Method  \
0      {"frequency": "", "identification": "tetramer-...   
1      {"frequency": "", "identification": "tetramer-...   
2      {"frequency": "", "identification": "tetramer-...   
3      {"frequency": "", "identification": "tetramer-...   
4      {"frequency": "", "identification": "tetramer-...   
...                                                  ...   
25650  {"frequency": "1/11", "identification": "tetra...   
25651  {"frequency": "1/11", "identification": "tetra...   
25652  {"frequency": "1/11", "identification": "tetra...   
25653  {"frequency": "1/11", "identification": "tetra...   
25654  {"frequency": "2/11", "identification": "tetra...   

                                                    Meta  \
0      {"cell.subset": "CD8+", "clone.id": "", "donor...   
1      {"cell.subset": "CD8+", "clone.id": "", "donor...   
2      {"cell.subset": "CD8+", "clone.id": "", "donor...   
3      {"cell.subset": "CD8+", "clone.id": "", "donor...   
4      {"cell.subset": "CD8+", "clone.id": "", "donor...   
...                                                  ...   
25650  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25651  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25652  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25653  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25654  {"cell.subset": "CD8+", "clone.id": "", "donor...   

                                                 CDR3fix  Score  
0      {"cdr3": "CIVRAPGRADMRF", "cdr3_old": "CIVRAPG...      2  
1      {"cdr3": "CAVPSGAGSYQLTF", "cdr3_old": "CAVPSG...      2  
2      {"cdr3": "CAYRPPGTYKYIF", "cdr3_old": "CAYRPPG...      2  
3      {"cdr3": "CIVRAPGRADMRF", "cdr3_old": "CIVRAPG.

complex.id Gene              CDR3            V          J      Species  \
1               2  TRA    CAVPSGAGSYQLTF    TRAV20*01  TRAJ28*01  HomoSapiens   
8              12  TRA    CAVPSGAGSYQLTF    TRAV20*01  TRAJ28*01  HomoSapiens   
11             16  TRA      CAVSFGNEKLTF  TRAV12-2*01  TRAJ48*01  HomoSapiens   
12             17  TRA   CAVTHYGGSQGNLIF  TRAV12-2*01  TRAJ42*01  HomoSapiens   
15             21  TRA        CAVNNARLMF  TRAV12-2*01  TRAJ31*01  HomoSapiens   
...           ...  ...               ...          ...        ...          ...   
25640       29252  TRA   CVVNDLVDSNYQLIW  TRAV12-1*01  TRAJ33*01  HomoSapiens   
25641       29253  TRA      CAVSEVGNKLTF   TRAV8-6*01  TRAJ17*01  HomoSapiens   
25646       29258  TRA     CAVDTGTASKLTF    TRAV41*01  TRAJ44*01  HomoSapiens   
25650       29262  TRA  CAFLNAGGTSYGKLTF  TRAV38-1*01  TRAJ52*01  HomoSapiens   
25653       29265  TRA     CAVESYNTDKLIF    TRAV41*01  TRAJ34*01  HomoSapiens   

             MHC A MHC B MHC class     Epitope Epitope gene Epitope species  \
1         HLA-B*08   B2M      MHCI    FLKEKGGL          Nef           HIV-1   
8         HLA-B*08   B2M      MHCI    FLKEMGGL          Nef           HIV-1   
11        HLA-A*02   B2M      MHCI  ELAGIGILTV        MLANA     HomoSapiens   
12        HLA-A*02   B2M      MHCI  ELAGIGILTV        MLANA     HomoSapiens   
15        HLA-A*02   B2M      MHCI  ELAGIGILTV        MLANA     HomoSapiens   
...            ...   ...       ...         ...          ...             ...   
25640  HLA-A*24:01   B2M      MHCI   NYNYLYRLF        Spike      SARS-CoV-2   
25641  HLA-A*24:01   B2M      MHCI   QYIKWPWYI        Spike      SARS-CoV-2   
25646  HLA-A*24:01   B2M      MHCI   QYIKWPWYI        Spike      SARS-CoV-2   
25650  HLA-A*24:01   B2M      MHCI   QYIKWPWYI        Spike      SARS-CoV-2   
25653  HLA-A*24:01   B2M      MHCI   QYIKWPWYI        Spike      SARS-CoV-2   

           Reference                                             Method  \
1      PMID:15596521  {"frequency": "", "identification": "tetramer-...   
8      PMID:15596521  {"frequency": "", "identification": "tetramer-...   
11     PMID:12555663  {"frequency": "1/11", "identification": "cultu...   
12     PMID:12555663  {"frequency": "1/17", "identification": "cultu...   
15     PMID:12555663  {"frequency": "1/11", "identification": "cultu...   
...              ...                                                ...   
25640  PMID:34086357  {"frequency": "1/5", "identification": "tetram...   
25641  PMID:34086357  {"frequency": "2/4", "identification": "tetram...   
25646  PMID:34086357  {"frequency": "1/9", "identification": "tetram...   
25650  PMID:34086357  {"frequency": "1/11", "identification": "tetra...   
25653  PMID:34086357  {"frequency": "1/11", "identification": "tetra...   

                                                    Meta  \
1      {"cell.subset": "CD8+", "clone.id": "", "donor...   
8      {"cell.subset": "CD8+", "clone.id": "", "donor...   
11     {"cell.subset": "CD8+", "clone.id": "", "donor...   
12     {"cell.subset": "CD8+", "clone.id": "", "donor...   
15     {"cell.subset": "CD8+", "clone.id": "", "donor...   
...                                                  ...   
25640  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25641  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25646  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25650  {"cell.subset": "CD8+", "clone.id": "", "donor...   
25653  {"cell.subset": "CD8+", "clone.id": "", "donor...   

                                                 CDR3fix  Score  
1      {"cdr3": "CAVPSGAGSYQLTF", "cdr3_old": "CAVPSG...      2  
8      {"cdr3": "CAVPSGAGSYQLTF", "cdr3_old": "CAVPSG...      2  
11     {"cdr3": "CAVSFGNEKLTF", "cdr3_old": "CAVSFGNE...      0  
12     {"cdr3": "CAVTHYGGSQGNLIF", "cdr3_old": "CAVTH...      0  
15     {"cdr3": "CAVNNARLMF", "cdr3_old": "CAVNNARLMF...      0  
...                                                  ...    ...  
2

In [4]:
TCR_Predict_Target = set(VDJdb_TRA_Test["Epitope"].tolist())
print(type(TCR_Predict_Target))
print(TCR_Predict_Target)


TCR_Predict_Target = ['KPVPEVKIL', 'SIIAYTMSL', 'FMIDVQQWG', 'NLVPMVATV', 'AIKLDDKDP', 'MVNTVAGAMK', 'KLFIRQEEV']
# EBV = VDJdb_TRA[VDJdb_TRA["Epitope species"] == "EBV"]
# EBV_epitope = set(EBV["Epitope"].tolist())
# print(EBV_epitope)

<class 'set'>
{'KPVPEVKIL', 'FLIGCNYLG', 'QINDMILSL', 'LMCQPILLL', 'FLALCADSI', 'KIILFLALI', 'YLYDRLLRV', 'FTVLCLTPV', 'AVGVGKSAL', 'KQLIKVTLV', 'NLLKDCPAV', 'FLCWHTNCY', 'TAFTIPSI', 'ELTSMKYFV', 'RLPAKAPL', 'ILGFVFTLT', 'CLAVHECFV', 'CLGSLIYST', 'TLACFVLAA', 'GGETALALL', 'RIMTWLDMV', 'KMDYFSGQL', 'AVFDRKSDAK', 'KLYGLDWAEL', 'FLKEKGGL', 'RTIKVFTTV', 'VLWAHGFEL', 'TLLFLMSFT', 'MHVSFVMAYPEMLAA', 'GLIAIVMVT', 'LVGLMWLSY', 'VLLFLAFVV', 'EMMLFDWKV', 'AYAQKIFKI', 'VLAWLYAAV', 'SLLMWITQV', 'VFVQSVLPYFVATKLAKIRK', 'LPDDFTGCV', 'NPTIQKNVL', 'AVVQSELPYPEGS', 'VLQAVGACV', 'GMDYHNGHL', 'EEYLQAFTY', 'MTEYKLVVVGAGDVGKSALTIQLI', 'SIIAYTMSL', 'SLLMWITQC', 'RLARLALVL', 'NNSYECDIPIGAGIC', 'SGEGSFQPSQENP', 'DATYQRTRALVR', 'ELAGIGALTV', 'KLNIKLLGV', 'YTPSKLIEY', 'FVAAIFYLI', 'QVILLNKHI', 'GVYDYLVST', 'LSFKELLVY', 'RARLVSPKL', 'FMSEAKCWT', 'WPWYIWLGF', 'ALALLLLDR', 'AMDEFIEQY', 'FVMMSAPPA', 'SANNCTFEY', 'IMLCCMTSC', 'FMIDVQQWG', 'LDDKDPQFK', 'WSMATYYLF', 'LPKEITVAT', 'TLIGDCATV', 'PVTLACFVL', 'FLPRVFSAV', 

In [5]:
ffn = tm.models.EstimatorBinary()

In [6]:
ffn.read_vdjdb(
    fns=VDJdb_TRA_Train_path,
    fn_blosum=None,
    antigen_ids=TCR_Predict_Target,
    blosum_encoding=False,
    is_train=True,
    chains="tra"
)

Found 0 CDR3 observations with unkown amino acids out of 15393.
Found 0 antigen observations with unkown amino acids out of 15393.
Found 0 CDR3+antigen observations with unkown amino acids out of 15393, leaving 15393 observations.
Assembled 15393 single-chain observations into 15393 multiple chain observations.
Found 324 observations that match target antigen sequences out of 15393.
Found 324 observations and assigned to train data.


In [7]:
print("Shape of (CDR3,antigen) sequences: ",ffn.x_train.shape)
# print("The head of TCR sequences: ",ffn.x_train[0])
print("Shape of covariates: ",ffn.covariates_train.shape)
# print("The head of covariates: ",ffn.covariates_train[0:5])
print("Shape of target set: ",ffn.y_train.shape)
# print("The head of target set: ",ffn.y_train[0:5])


Shape of (CDR3,antigen) sequences:  (324, 1, 32, 26)
Shape of covariates:  (324, 0)
Shape of target set:  (324, 1)


In [9]:
print(ffn.x_train)

[[[[0. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 1. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 1.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 1. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 1.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 1.]]]


 ...


 [[[0. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 1. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 1.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 1.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [1. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. 

In [10]:
print(np.unique(ffn.y_train))

[1.]


In [12]:
ffn.assign_clonotype(flavor="manhatten")

Found 242 clonotypes for 324 observations.


In [13]:
#max_obs: Maximum number of observations per clonotype.
ffn.downsample_clonotype(max_obs=10)

Downsampled 242 clonotypes from 324 cells to 319 cells.


In [14]:
print("Shape of (CDR3,antigen) sequences: ",ffn.x_train.shape)

Shape of (CDR3,antigen) sequences:  (319, 1, 32, 26)


In [16]:
#Clear test set.
ffn.clear_test_data()
ffn.read_vdjdb(
    fns=VDJdb_TRA_Test_path,
    fn_blosum=None,
    blosum_encoding=False,
    is_train=False,
    chains="tra"
)
#ffn.remove_overlapping_antigens(data="test")
#Assign clonotype by Manhatten distance.
ffn.assign_clonotype(flavor="manhatten", data="test")
#Downsample clonotypes to data stored in x_test.
ffn.downsample_clonotype(max_obs=10, data="test")
# Sample negative binding pairs for training.
#ffn.sample_negative_data(is_train=False)

Found 0 CDR3 observations with unkown amino acids out of 10262.
Found 0 antigen observations with unkown amino acids out of 10262.
Found 0 CDR3+antigen observations with unkown amino acids out of 10262, leaving 10262 observations.
Assembled 10262 single-chain observations into 10262 multiple chain observations.


AssertionError: Pre-set antigen length (10) is smaller than found antigen length 25.

In [11]:
print("Shape of (CDR3,antigen) sequences for training: ",ffn.x_train.shape)
print("Shape of target set for training: ",ffn.y_train.shape)
print("Shape of (CDR3,antigen) sequences for test: ",ffn.x_test.shape)
print("Shape of target set for test: ",ffn.y_test.shape)

Shape of (CDR3,antigen) sequences for training:  (14121, 1, 51, 26)
Shape of target set for training:  (14121, 1)
Shape of (CDR3,antigen) sequences for test:  (9888, 1, 51, 26)
Shape of target set for test:  (9888, 1)


In [11]:
print(np.unique(ffn.y_train))
print(np.unique(ffn.y_test))

[1.]
[None]


In [12]:
ffn.downsample_data(n=5000, data="train")
ffn.downsample_data(n=8000, data="test")

Downsampled train data from 14121 cells to 5000 cells.
Downsampled test data from 9888 cells to 8000 cells.


In [13]:
print("Shape of TCR CDR3 sequences for training: ",ffn.x_train.shape)
print("Shape of TCR CDR3 sequences for test: ",ffn.x_test.shape)

Shape of TCR CDR3 sequences for training:  (5000, 1, 51, 26)
Shape of TCR CDR3 sequences for test:  (8000, 1, 51, 26)


In [14]:
ffn.build_self_attention(
    residual_connection=True,
    aa_embedding_dim=0,
    attention_size=[5, 5],
    attention_heads=[4, 4],
    optimizer='adam',
    lr=0.001,
    loss='bce',
    label_smoothing=0
)

D:\Anaconda Python\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [42]:
 ffn.train(
    epochs=1,
    batch_size=8
    )

Number of observations in evaluation data: 497
Number of observations in training data: 4503
100/100 - 3s - loss: 0.0091 - keras_acc: 0.9975 - keras_precision: 1.0000 - keras_recall: 0.9975 - keras_auc: 0.0000e+00 - keras_fn: 2.0000 - keras_fp: 0.0000e+00 - keras_tn: 0.0000e+00 - keras_tp: 798.0000 - keras_ce: 0.0091 - val_loss: 1.3588e-05 - val_keras_acc: 1.0000 - val_keras_precision: 1.0000 - val_keras_recall: 1.0000 - val_keras_auc: 0.0000e+00 - val_keras_fn: 0.0000e+00 - val_keras_fp: 0.0000e+00 - val_keras_tn: 0.0000e+00 - val_keras_tp: 256.0000 - val_keras_ce: 1.3588e-05 - lr: 0.0010 - 3s/epoch - 27ms/step


In [15]:
ffn.evaluate()
ffn.evaluations
ffn.predict()


63/63 [==============================] - 1s 14ms/step


In [21]:
print(ffn.predictions.shape)
print(ffn.y_test.shape)

(8000, 1)
(8000, 1)


In [56]:
ffn.model.training_model.summary()

Model: "model_sa"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_tcr (InputLayer)         [(None, 1, 51, 26)]  0           []                               
                                                                                                  
 tf.compat.v1.squeeze_1 (TFOpLa  (None, 51, 26)      0           ['input_tcr[0][0]']              
 mbda)                                                                                            
                                                                                                  
 tf.math.subtract_1 (TFOpLambda  (None, 51, 26)      0           ['tf.compat.v1.squeeze_1[0][0]'] 
 )                                                                                                
                                                                                           

In [21]:
fn_tmp = 'test_model'
ffn.save_model_tf2(fn_tmp)

INFO:tensorflow:Assets written to: test_model\assets


INFO:tensorflow:Assets written to: test_model\assets


In [24]:
ffn2 = tm.models.EstimatorBinary()
ffn2.load_model_tf2(fn_tmp)
ffn2.evaluate()
ffn.evaluations
ffn2.predict()


AttributeError: 'EstimatorBinary' object has no attribute 'model'